acloud: fix py3 compatible issue: "AttributeError" of 'filter' object has no attribute 'append'
Wrap with list(filter..)) since filter return list in py2 but
return type of 'filter' in py3.
Although gcompute_client didn't call 'append', it also should wrap with
list.

BUG: 137195528
Test: acloud-dev create --local-image
Change-Id: I87af280fe4a41e014c0352d0bfb2db45b0796132